crudApp/urls.py
from django.conf.urls import url, include
from crudApp import views

urlpatterns = [
    url(r'^$', views.getStudents, name='students_list'),
    url(r'^create/$', views.createStudent, name="create"),
    url(r'^update/(?P<id>\d+)/$', views.updateStudent, name='update'),
    url(r'^delete/(?P<id>\d+)/$', views.deleteStudent, name='delete'),
    url(r'^logout/$', views.logout),
    # class based views urls
    url(r'^cbv/$', views.StudentListView.as_view(), name='cbv_student_list'),
    url(r'^cbv/(?P<pk>\d+)/$', views.StudentDetailView.as_view(),
        name='cbv_student_detail'),
    url(r'^cbv/create', views.StudentCreateView.as_view(), name='cbv_create'),
    url(r'^cbv/update/(?P<pk>\d+)$',
        views.StudentUpdateView.as_view(), name='cbv_update'),
    url(r'^cbv/delete/(?P<pk>\d+)$',
        views.StudentDeleteView.as_view(), name='cbv_delete')
]

django_basics/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from hello.views import index
from crudApp.views import logout
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index),
    url(r'^urlapp/', include('urlApp.urls')),
    url(r'^templateApp/', include('templateApp.urls')),
    url(r'^modelApp/', include('modelApp.urls')),
    url(r'^formsApp/', include('formsApp.urls')),
    url(r'^crudApp/', include('crudApp.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^sessionApp/', include('sessionApp.urls')),

]

urlApp/urls.py
from django.conf.urls import url
from urlApp.views import get_time, get_id, get_user, get_user_details

urlpatterns = [
    url(r'^time/$', get_time),
    url(r'^time/(\d+)/$', get_time),
    url(r'^(?P<id>\d+)/$', get_id),
    url(r'^(?P<username>\w+)/$', get_user),
    url(
        r'^(?P<username>\w+)/(?P<id>\d+)/(?P<email>[\w.@-]+)/$', get_user_details),

]

crudApp/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.


class Student(models.Model):
    course_choices = [('python', 'Python'), ('java', 'Java'),
                      ('django', 'Django'), ('flask', 'Flask')]
    fullname = models.CharField(max_length=20)
    course = models.CharField(max_length=10, choices=course_choices)
    fee = models.FloatField()

    def __repr__(self):
        return self.fullname

    def get_absolute_url(self):
        return reverse('cbv_student_detail', kwargs={'pk': self.pk})

crudApp/forms.py
from django import forms
from crudApp.models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

crudApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from crudApp.models import Student
from crudApp.forms import StudentForm
from django.contrib import messages

# Create your views here.


@login_required
def getStudents(request):
    students = Student.objects.all()
    return render(request, 'crudApp/home.html', {'stds': students})


@login_required
def createStudent(request):
    form = StudentForm()
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Student Created Successfully')
            return redirect('students_list')
    return render(request, 'crudApp/create.html', {'form': form})


@login_required
def updateStudent(request, id):
    student = Student.objects.get(id=id)
    if student:
        form = StudentForm(instance=student)
        if request.method == 'POST':
            form = StudentForm(request.POST, instance=student)
            if form.is_valid():
                form.save()
                messages.success(
                    request, 'Sudent Details Updated successfully')
                return redirect('students_list')
    return render(request, 'crudApp/update.html', {'form': form})


@login_required
@permission_required('crudApp.student_delete')
def deleteStudent(request, id):
    student = Student.objects.get(id=id)
    if student:
        student.delete()
        messages.success(request, 'Sudent Deleted Successfully')
    else:
        messages.error(request, f'Student with {id} not avilable')
    return redirect('students_list')


def logout(request):
    return render(request, 'crudApp/logout.html')


# implementing crud operation using class based views
class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    # default template_name is modelName_list.html i.e student_list.html
    # default context_object_name is modelName_list i.e. student_list


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student
    # default template_name is modelName_detail.html i.e student_detail.html
    # default context_object_name is modelName in lower case i.e. student


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Student
    fields = ('fullname', 'course', 'fee')
    # default template_name is modelName_form.html i.e student_form.html
    # default context_object_name is form


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    fields = ('course', 'fee')
    # default template_name is modelName_form.html i.e student_form.html
    # default context_object_name is form


class StudentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Student
    permission_required='crudApp.student_delete'
    success_url = reverse_lazy('cbv_student_list')

templates/crudApp/create.html
{% extends 'templateApp/base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        <table>
            {% csrf_token %}
            {{form.as_table}}
        </table>
        <input type="submit" value="Create">
    </form>
</div>
{% endblock content %}

templates/crudApp/home.html
{% extends 'templateApp/base.html' %}

{% block content %}
<div class="container">
    <h1>Student Details</h1>
    <br><a href="{% url 'create' %}">Add a New Student</a>
    <table border="2">
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Course</td>
            <td>Fee</td>
        </tr>

        {% for student in stds %}
        <tr>
            <td>{{student.id}}</td>
            <td>{{student.fullname}}</td>
            <td>{{student.course}}</td>
            <td>{{student.fee}}</td>
            <td><a href="{% url 'update' student.id %}">Update</a></td>

            {% if perms.crudApp.delete_student %}
            <td><a href="{% url 'delete' student.id %}">Delete</a></td>
            {% endif %}


        </tr>
        {% endfor %}

    </table>
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/crudApp/logout.html
<h1>Logout Successfully</h1>
<span><a href="{% url 'students_list' %}"><i>Click Here</i></a> to Log In again</span>

templates/crudApp/student_confirm_delete.html
{% extends 'templateApp/base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <h3>Do you want to Delete?</h3>
        <input type="submit" value="Delete">
    </form>
    <a href="{% url 'cbv_student_list' %}">Cancel</a>
</div>
{% endblock content %}

templates/crudApp/student_detail.html
{% extends 'templateApp/base.html' %}

{% block content %}
<div class="container">
    <ul>
        <li>
            <h3>Full Name : {{ student.fullname | title }}</h3>
        </li>
        <li>
            <h3>Course : {{ student.course | title }}</h3>
        </li>
        <li>
            <h3>Fee : {{ student.fee }}</h3>
        </li>
    </ul>
    <a href="{% url 'cbv_student_list' %}">Students List</a>
    <br>
    <a href="{% url 'cbv_update' student.id %}">Update</a>
    <br>
    {% if perms.crudApp.delete_student %}
    <a href="{% url 'cbv_delete' student.id %}">Delete</a>
    {% endif %}

</div>
{% endblock content %}

templates/crudApp/student_form.html
{% extends 'templateApp/base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock content %}

templates/crudApp/student_list.html
{% extends 'templateApp/base.html' %}

{% block content %}
<div class="container">
    <h1>Student Details</h1>
    <br><a href="{% url 'cbv_create' %}">Add a New Student</a>
    <table border="2">
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Course</td>
            <td>Fee</td>
        </tr>

        {% for student in student_list %}
        <tr>
            <td><a href="{% url 'cbv_student_detail' student.id%}">{{student.id}}</a></td>
            <td>{{student.fullname}}</td>
            <td>{{student.course}}</td>
            <td>{{student.fee}}</td>
        </tr>
        {% endfor %}

    </table>
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/crudApp/update.html
{% extends 'templateApp/base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        <table>
            {% csrf_token %}
            {{form.as_table}}
        </table>
        <input type="submit" value="Update">
    </form>
</div>
{% endblock content %}